---
title: "Logistic Model"
output: github_document
---

```{r load-packages, include = FALSE}
library(rmarkdown)
library(tidyverse)
library(tidymodels)
library(knitr)
```

```{r read_csv, include = FALSE}
banking_train<- read_delim("/cloud/project/data/Banking Dataset.csv",
            delim = ";", escape_double = FALSE, trim_ws = TRUE)
```


```{r modify_df}
banking_train <- banking_train %>%
  mutate(y = factor(if_else(y == "yes", 1, 0))) #Changed Outcome Variable to Factor Type
```

```{r split_csv}

set.seed(45221)

#80-20 Split of Data

banking_split <- initial_split(banking_train, prop = 0.8)
reduced_train_df <-training(banking_split)
banking_test <-testing(banking_split)
nrow(banking_train)
nrow(banking_test)
```

```{r recipe}
#Model Recipe
banking_rec<- recipe(
  y ~ .,
  data = reduced_train_df
)

banking_rec <- banking_rec %>%
  step_rm( pdays) %>% #Removed this variable due to low impact on model.
  step_cut(campaign, previous, breaks = c(0, 1)) %>% #Only care about values x = 0 and x >= 1 for these variables.
  step_cut(age, breaks = c(25,40,65)) %>% #Created age groups
  step_cut(balance, breaks = c(-0.1, 0.1, 1000, 10000)) %>% #Created balance groups
  step_cut(day, breaks = c(10,20)) %>% #Categorized days variable into beginning, middle, or end of the month.
  step_cut(duration, breaks = c(60, 120, 180, 240, 300, 360, 420, 480, 540, 600)) %>% #Divided Calls by duration in minutes.
  step_dummy(all_nominal(),-all_outcomes()) %>% #Created Dummy Variables
  step_zv(all_predictors()) #Removed Zero Variance Variables
```

```{r banking_logistic_model}
banking_mod <- logistic_reg() %>%
  set_engine("glm")
```

```{r workflow}
banking_wflow <-workflow() %>%
  add_model(banking_mod) %>%
  add_recipe(banking_rec)
```


```{r fit}
 banking_fit <- banking_wflow %>%
  fit(data = reduced_train_df)
tidy(banking_fit) 
```

```{r prediction}
banking_pred <- predict(banking_fit, banking_test, type = "prob") %>%
  bind_cols(banking_test %>% select(y))

banking_pred %>%
  roc_curve(
    truth = y,
    .pred_1,
    event_level = "second") %>%
  autoplot()

banking_pred %>%
  roc_auc(
    truth = y,
    .pred_1,
    event_level = "second") 

```

```{r prediction_matrix}
cutoff <- 0.5
banking_pred %>%
  mutate(
    subscribed = if_else(y == 1, "Client Subscribed", "Client did not Subscribe"),
    subscribed_pred = if_else(.pred_1>cutoff, "Client Predicted to Subscribe", "Client Predicted to Not Subscribe") )%>%
      count(subscribed_pred, subscribed) %>%
      pivot_wider(names_from = subscribed, values_from = n) %>%
      kable(col.names = c("","Client did not Subscribe", "Client Subscribed")
  )
```

```{r cross-validation}
set.seed(777)

folds <-vfold_cv(banking_train, v = 10)
#Divided data into ten folds because of the large dataset size.

banking_fit_cross<- banking_wflow %>%
  fit_resamples(folds)

banking_fit_cross

collect_metrics(banking_fit_cross)

```
```{r Final_Test}

banking_test_final <- read_csv("/cloud/project/data/banking_test.csv")

banking_test_final <- banking_test_final %>%
  mutate(y = factor(if_else(y == "yes", 1, 0))) #Changed Outcome Variable to Factor Type
  

banking_final_pred <- predict(banking_fit, banking_test_final, type = "prob") %>%
  bind_cols(banking_test_final %>% select(y))

banking_final_pred %>%
  roc_curve(
    truth = y,
    .pred_1,
    event_level = "second") %>%
  autoplot()

banking_final_pred %>%
  roc_auc(
    truth = y,
    .pred_1,
    event_level = "second") 

```

```{r prediction_matrix_final}
cutoff <- 0.5
banking_final_pred %>%
  mutate(
    subscribed = if_else(y == 1, "Client Subscribed", "Client did not Subscribe"),
    subscribed_pred = if_else(.pred_1>cutoff, "Client Predicted to Subscribe", "Client Predicted to Not Subscribe") )%>%
      count(subscribed_pred, subscribed) %>%
      pivot_wider(names_from = subscribed, values_from = n) %>%
      kable(col.names = c("","Client did not Subscribe", "Client Subscribed")
  )
```

```

