---
title: "Code Tester"
output: github_document
---

```{r load-packages, include = FALSE}
# Add any additional packages you need to this chunk
library(rmarkdown)
library(tidyverse)
library(tidymodels)
library(knitr)
library(revealjs)
```


```{r read_csv}
banking_train<- read_delim("/cloud/project/data/Banking Dataset.csv",
            delim = ";", escape_double = FALSE, trim_ws = TRUE)
```

```{r modify_df}
banking_train <- banking_train %>%
  mutate(y = factor(if_else(y == "yes", 1, 0)))
```

```{r split_csv}

set.seed(45211)
######
banking_split <- initial_split(banking_train, prop = 0.8)
reduced_train_df <-training(banking_split)
banking_test <-testing(banking_split)
glimpse(reduced_train_df)
glimpse(banking_test)
```

```{r initial_logistic_model}
trial_fit <- logistic_reg() %>%
  set_engine("glm") %>%
  fit(y ~ ., data = reduced_train_df, family = "binomial")
trial_fit
```

```{r}
banking_pred <- predict(trial_fit, banking_test, type = "prob") %>%
  bind_cols(banking_test %>% select(y))

banking_pred %>%
  roc_curve(
    truth = y,
    .pred_1,
    event_level = "second") %>%
  autoplot()

banking_pred %>%
  roc_auc(
    truth = y,
    .pred_1,
    event_level = "second") 

```
```{r 17x17 grid}


```


