---
title: "Code Tester"
output: github_document
---

```{r load-packages, include = FALSE}
# Add any additional packages you need to this chunk
library(rmarkdown)
library(tidyverse)
library(tidymodels)
library(knitr)
library(revealjs)
library(GGally)
```


```{r read_csv}
banking_train<- read_delim("/cloud/project/data/Banking Dataset.csv",
            delim = ";", escape_double = FALSE, trim_ws = TRUE)
rename(banking_train, yes=y)
```

```{r modify_df}
banking_train <- banking_train %>%
  mutate(y = factor(if_else(y == "yes", 1, 0)))
```

```{r split_csv}

set.seed(45211)
######
banking_split <- initial_split(banking_train, prop = 0.8)
reduced_train_df <-training(banking_split)
banking_test <-testing(banking_split)
nrow(banking_train)
nrow(banking_test)
```

```{r recipe}
banking_rec<- recipe(
  y ~ .,
  data = reduced_train_df
)

banking_rec <- banking_rec %>%
  step_rm(day, pdays) %>%
  step_cut(campaign, previous, breaks = c(0, 1)) %>%
  step_cut(age, breaks = c(25,40,65)) %>%
  step_cut(balance, breaks = c(-0.1, 0.1, 1000, 10000)) %>%
  step_cut(duration, breaks = c(60, 120, 180, 240, 300, 360, 420, 480, 540, 600)) %>%
  step_dummy(all_nominal(),-all_outcomes()) %>%
  step_zv(all_predictors())
```

```{r banking_logistic_model}
banking_mod <- logistic_reg() %>%
  set_engine("glm")
```

```{r workflow}
banking_wflow <-workflow() %>%
  add_model(banking_mod) %>%
  add_recipe(banking_rec)
```


```{r fit}
 banking_fit <- banking_wflow %>%
  fit(data = reduced_train_df)
tidy(banking_fit) 
```

```{r prediction}
banking_pred <- predict(banking_fit, banking_test, type = "prob") %>%
  bind_cols(banking_test %>% select(y))

banking_pred %>%
  roc_curve(
    truth = y,
    .pred_1,
    event_level = "second") %>%
  autoplot()

banking_pred %>%
  roc_auc(
    truth = y,
    .pred_1,
    event_level = "second") 

```

```{r 17 graph grid}
banking_train%>%
  ggplot(aes(x=job,y=y))+
  geom_jitter()
banking_train%>%
  ggplot(aes(x=marital,y=y))+
  geom_jitter()
banking_train%>%
  ggplot(aes(x=education,y=y))+
  geom_jitter()
banking_train%>%
  ggplot(aes(x=default,y=y))+
  geom_jitter()
banking_train%>%
  ggplot(aes(x=housing,y=y))+
  geom_jitter()
banking_train%>%
  ggplot(aes(x=loan,y=y))+
  geom_jitter()
banking_train%>%
  ggplot(aes(x=contact,y=y))+
  geom_jitter()
banking_train%>%
  ggplot(aes(x=month,y=y))+
  geom_jitter()
banking_train%>%
  ggplot(aes(x=poutcome,y=y))+
  geom_jitter()
banking_train%>%
  ggplot(aes(x=age,y=y))+
  geom_point()
banking_train%>%
  ggplot(aes(x=balance,y=y))+
  geom_point()
banking_train%>%
  ggplot(aes(x=day,y=y))+
  geom_point()
banking_train%>%
  ggplot(aes(x=duration,y=y))+
  geom_point()
banking_train%>%
  ggplot(aes(x=campaign,y=y))+
  geom_point()
banking_train%>%
  ggplot(aes(x=pdays,y=y))+
  geom_point()
banking_train%>%
  ggplot(aes(x=previous,y=y))+
  geom_point()
```


